# Generated by Django 3.0.3 on 2020-03-28 17:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Описание задачи')),
                ('status', models.CharField(choices=[('waiting', 'Ожидает принятия'), ('working', 'В работе'), ('finished', 'Завершено')], default='waiting', max_length=8, verbose_name='Статус')),
                ('until_to', models.DateTimeField(verbose_name='Сроком до')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('finished_at', models.DateTimeField(verbose_name='Дата завершения')),
                ('for_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_task_set', to=settings.AUTH_USER_MODEL)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employer_task_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
