# Generated by Django 3.0.3 on 2020-04-01 15:11

import control.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0002_finished_at_null'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=control.models.get_file_path, verbose_name='Файл')),
                ('title', models.CharField(max_length=64, verbose_name='Название файла')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.Task')),
            ],
        ),
    ]
